
import 'bootstrap/dist/css/bootstrap.css';
import type { GetServerSidePropsContext, Metadata } from "next";
// import localFont from "next/font/local";
import "./globals.css";
import { getServerSideProps } from './page';
import buildClient from './api/build-client';


export const metadata: Metadata = {
  title: "Ticket app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

export function getServerSideProps(context: GetServerSidePropsContext) {
  const client = buildClient(context)

}
